"""
ML-based insights and analytics module
Provides intelligent recommendations based on user behavior
"""
from datetime import datetime, timedelta
from models.firebase_models import User, Task, Expense

class InsightsGenerator:
    """
    Generates intelligent insights about tasks and expenses
    Module 6: Analytics & Insights Module (Explainable AI)
    
    Uses rule-based logic only for full transparency and explainability.
    No black-box ML models - all logic is transparent and viva-ready.
    
    Features:
    - Task productivity analysis
    - Expense trend analysis
    - Combined productivity/financial health correlation
    - Risk level prediction (Low/Medium/High) with detailed explanation
    - Actionable recommendations
    
    Design Principle:
    Every insight is generated by explicit, understandable rules.
    Users can understand exactly why they're getting a specific insight.
    """
    
    def __init__(self, user_id):
        self.user_id = user_id
        self.insights = []
    
    def generate_all_insights(self):
        """
        Generate all available insights
        Returns a dictionary with task and expense insights
        """
        return {
            'task_insights': self.get_task_insights(),
            'expense_insights': self.get_expense_insights(),
            'combined_insights': self.get_combined_insights()
        }
    
    def get_task_insights(self):
        """
        Generate insights about task management
        Includes: overdue tasks, high-priority tasks, completion rate
        """
        insights = []
        
        # Get all tasks for user - using Firebase model method
        user_tasks = Task.query_by_user(self.user_id)
        
        if not user_tasks:
            return ["No tasks created yet. Start by adding a task!"]
        
        # Count overdue high-priority tasks
        overdue_high_priority = [
            t for t in user_tasks 
            if t.is_overdue() and t.priority == Task.PRIORITY_HIGH
        ]
        
        if overdue_high_priority:
            insights.append(
                f"⚠️ WARNING: You have {len(overdue_high_priority)} overdue high-priority task(s). "
                f"Consider completing them urgently!"
            )
        
        # Count all overdue tasks
        overdue_tasks = [t for t in user_tasks if t.is_overdue()]
        if overdue_tasks and overdue_high_priority == []:
            insights.append(
                f"📌 You have {len(overdue_tasks)} overdue task(s). Please review and complete them."
            )
        
        # Calculate completion rate
        completed_tasks = [t for t in user_tasks if t.status == Task.STATUS_COMPLETED]
        completion_rate = (len(completed_tasks) / len(user_tasks) * 100) if user_tasks else 0
        
        if completion_rate >= 80:
            insights.append(
                f"🎉 Excellent! You have a {completion_rate:.0f}% task completion rate. Keep it up!"
            )
        elif completion_rate >= 50:
            insights.append(
                f"👍 Good progress! You have {completion_rate:.0f}% task completion rate."
            )
        else:
            insights.append(
                f"📝 Your completion rate is {completion_rate:.0f}%. Try to focus on pending tasks."
            )
        
        # Count high-priority pending tasks
        pending_high_priority = [
            t for t in user_tasks 
            if t.status == Task.STATUS_PENDING and t.priority == Task.PRIORITY_HIGH
        ]
        
        if len(pending_high_priority) >= 3:
            insights.append(
                f"🔴 You have {len(pending_high_priority)} high-priority pending tasks. "
                f"Consider prioritizing these!"
            )
        
        # Tasks due soon (within 3 days)
        now = datetime.utcnow()
        due_soon = [
            t for t in user_tasks
            if t.deadline and 0 < (t.deadline - now).days <= 3 
            and t.status == Task.STATUS_PENDING
        ]
        
        if due_soon:
            insights.append(
                f"⏰ {len(due_soon)} task(s) are due within the next 3 days. Plan accordingly!"
            )
        
        return insights if insights else ["Keep tracking your tasks for better insights!"]
    
    def get_expense_insights(self):
        """
        Generate insights about expense patterns
        Uses rule-based logic to detect overspending and trends
        """
        insights = []
        
        # Get expenses for current and previous month
        now = datetime.utcnow()
        current_month_start = datetime(now.year, now.month, 1)
        
        if now.month == 1:
            previous_month_start = datetime(now.year - 1, 12, 1)
        else:
            previous_month_start = datetime(now.year, now.month - 1, 1)
        
        # Get all expenses and filter in Python
        all_expenses = Expense.query_by_user(self.user_id)
        current_month_expenses = [
            e for e in all_expenses 
            if (e.date if isinstance(e.date, datetime) else datetime.fromisoformat(e.date)) >= current_month_start
        ]
        
        previous_month_expenses = [
            e for e in all_expenses 
            if ((e.date if isinstance(e.date, datetime) else datetime.fromisoformat(e.date)) >= previous_month_start and 
                (e.date if isinstance(e.date, datetime) else datetime.fromisoformat(e.date)) < current_month_start)
        ]
        
        if not current_month_expenses and not previous_month_expenses:
            return ["No expenses recorded yet. Start tracking to get insights!"]
        
        # Calculate totals
        current_total = sum(e.amount for e in current_month_expenses)
        previous_total = sum(e.amount for e in previous_month_expenses)
        
        # Overspending detection (Rule-based)
        if previous_total > 0:
            month_change = ((current_total - previous_total) / previous_total) * 100
            
            if month_change > 20:
                insights.append(
                    f"💸 ALERT: Your spending increased by {month_change:.1f}% compared to last month! "
                    f"Current: ₹{current_total:.2f} vs Previous: ₹{previous_total:.2f}"
                )
            elif month_change < -20:
                insights.append(
                    f"✅ Great! Your spending decreased by {abs(month_change):.1f}% compared to last month!"
                )
        
        if current_total > 0:
            insights.append(
                f"💰 Total spending this month: ₹{current_total:.2f}"
            )
        
        # Category-wise analysis
        category_totals = {}
        for expense in current_month_expenses:
            if expense.category not in category_totals:
                category_totals[expense.category] = 0
            category_totals[expense.category] += expense.amount
        
        if category_totals:
            # Find highest spending category
            highest_category = max(category_totals, key=category_totals.get)
            highest_amount = category_totals[highest_category]
            
            insights.append(
                f"📊 Highest spending category: {highest_category} (₹{highest_amount:.2f})"
            )
        
        # High expense detection (threshold: ₹100 in a day)
        high_expenses = [e for e in current_month_expenses if e.amount > 100]
        if high_expenses:
            insights.append(
                f"⚡ You have {len(high_expenses)} large expense(s) this month "
                f"(over ₹100 each)"
            )
        
        # Average daily spending
        days_in_month = (current_month_start.replace(day=28) + timedelta(days=4)).replace(day=1) - timedelta(days=1)
        daily_average = current_total / days_in_month.day if current_total > 0 else 0
        
        insights.append(
            f"📈 Average daily spending: ₹{daily_average:.2f}"
        )
        
        return insights if insights else ["Keep tracking expenses for detailed insights!"]
    
    def get_combined_insights(self):
        """
        Generate combined insights about productivity and financial health
        """
        insights = []
        
        # Get user data - using Firebase models
        user_tasks = Task.query_by_user(self.user_id)
        user_expenses = Expense.query_by_user(self.user_id)
        
        if not user_tasks or not user_expenses:
            return ["Track both tasks and expenses for comprehensive insights!"]
        
        # Task completion rate
        completed = len([t for t in user_tasks if t.status == Task.STATUS_COMPLETED])
        completion_rate = (completed / len(user_tasks) * 100) if user_tasks else 0
        
        # Expense trend
        now = datetime.utcnow()
        current_month_start = datetime(now.year, now.month, 1)
        current_expenses = [
            e for e in user_expenses 
            if (e.date if isinstance(e.date, datetime) else datetime.fromisoformat(e.date)) >= current_month_start
        ]
        
        current_spending = sum(e.amount for e in current_expenses)
        
        # Combined analysis
        if completion_rate >= 70 and current_spending < 500:
            insights.append(
                "🌟 Excellent! High productivity and controlled spending. You're doing great!"
            )
        elif completion_rate >= 50 and current_spending < 1000:
            insights.append(
                "👍 Good balance between productivity and spending. Continue this trend!"
            )
        else:
            insights.append(
                "💡 Focus on improving either task completion or expense control."
            )
        
        return insights
    
    def predict_high_risk_month(self):
        """
        Simple ML-based prediction: Detect if upcoming month might be 'high risk'
        Based on: Overdue tasks + High spending trend
        Returns: Risk level (Low, Medium, High) with explanation
        """
        # Get metrics - using Firebase models
        user_tasks = Task.query_by_user(self.user_id)
        
        # Count overdue tasks
        overdue_count = len([t for t in user_tasks if t.is_overdue()])
        
        # Get recent spending (last 30 days) and user balance/budget
        now = datetime.utcnow()
        user_expenses = Expense.query_by_user(self.user_id)
        last_30_expenses = [
            e for e in user_expenses 
            if (e.date if isinstance(e.date, datetime) else datetime.fromisoformat(e.date)) >= now - timedelta(days=30)
        ]
        total_last_30 = sum(e.amount for e in last_30_expenses)
        user = User.get_by_id(self.user_id)
        balance = (user.balance_amount or 0) if user else 0
        budget = (user.monthly_budget or 0) if user else 0
        
        # Risk scoring (rule-based)
        risk_score = 0
        
        # Factor 1: Overdue tasks
        if overdue_count >= 3:
            risk_score += 2
        elif overdue_count >= 1:
            risk_score += 1
        
        # Factor 2: Balance vs spending (30d)
        if balance <= 0 and total_last_30 > 0:
            risk_score += 2
        elif total_last_30 > balance * 0.8:
            risk_score += 1
        
        # Factor 3: Budget overrun
        if budget > 0 and total_last_30 > budget:
            risk_score += 1
        
        # Determine risk level
        if risk_score >= 3:
            risk_level = 'High'
            explanation = (
                f"High risk detected: {overdue_count} overdue tasks + recent spending of "
                f"₹{total_last_30:.2f} with balance ₹{balance:.2f}. Consider reducing expenses and clearing overdue tasks."
            )
        elif risk_score >= 1:
            risk_level = 'Medium'
            explanation = (
                f"Moderate risk: {overdue_count} overdue tasks or spending (₹{total_last_30:.2f} last 30d) nearing balance ₹{balance:.2f}. Monitor closely."
            )
        else:
            risk_level = 'Low'
            explanation = (
                f"Low risk: Spending ₹{total_last_30:.2f} in last 30d with balance ₹{balance:.2f}. Keep it up!"
            )
        
        return {
            'risk_level': risk_level,
            'explanation': explanation,
            'metrics': {
                'overdue_tasks': overdue_count,
                'last_30d_spending': round(total_last_30, 2),
                'remaining_balance': round(balance, 2),
                'budget': round(budget, 2),
                'risk_score': risk_score
            }
        }
